#include "palette.hpp"

#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>

#include <thread>
#include <vector>

#include "config.hpp"
#include "cpp/palettes/tones.h"
#include "cpp/quantize/celebi.h"
#include "cpp/score/score.h"
#include "cpp/utils/utils.h"
#include "wallpaper.hpp"

namespace mcu = material_color_utilities;

namespace fenriz::desktop::palette {

    namespace {

        std::string hex(mcu::Argb argb) {
            char buf[8];
            g_snprintf(buf, sizeof buf, "#%06x", argb & 0xffffff);
            return buf;
        }

        std::string define(const char* name, mcu::Argb argb) {
            return std::string("@define-color ") + name + " " + hex(argb) + ";\n";
        }

    } // namespace

    std::optional<uint32_t> seed(const std::string& image) {
        // The cached thumbnail is plenty for quantizing and saves decoding the full image.
        const std::string thumb = wallpaper::ensure_thumbnail(image);
        if (thumb.empty())
            return std::nullopt;
        GdkPixbuf* pixbuf = gdk_pixbuf_new_from_file(thumb.c_str(), nullptr);
        if (!pixbuf)
            return std::nullopt;

        const int width = gdk_pixbuf_get_width(pixbuf);
        const int height = gdk_pixbuf_get_height(pixbuf);
        const int stride = gdk_pixbuf_get_rowstride(pixbuf);
        const int channels = gdk_pixbuf_get_n_channels(pixbuf);
        const guchar* data = gdk_pixbuf_read_pixels(pixbuf);

        std::vector<mcu::Argb> pixels;
        pixels.reserve(static_cast<size_t>(width) * height);
        for (int y = 0; y < height; y++) {
            const guchar* p = data + y * stride;
            for (int x = 0; x < width; x++, p += channels)
                pixels.push_back(mcu::ArgbFromRgb(p[0], p[1], p[2]));
        }
        g_object_unref(pixbuf);

        // RankedSuggestions falls back to Google blue, so it is never empty.
        return mcu::RankedSuggestions(mcu::QuantizeCelebi(pixels, 128).color_to_count).front();
    }

    std::string css(uint32_t seed) {
        const mcu::Hct hct(seed);
        const double hue = hct.get_hue();
        // Material 3 tonal spot, the scheme matugen uses by default.
        const mcu::TonalPalette primary(hue, 36.0);
        const mcu::TonalPalette tertiary(hue + 60.0, 24.0);
        const mcu::TonalPalette neutral(hue, 6.0);
        const mcu::TonalPalette variant(hue, 8.0);
        const mcu::TonalPalette error(25.0, 84.0);

        return define("fenriz_accent", primary.get(80)) + define("fenriz_accent2", tertiary.get(80)) +
               define("fenriz_on_accent", primary.get(20)) + define("fenriz_error", error.get(80)) +
               define("theme_bg_color", neutral.get(12)) + define("window_bg_color", neutral.get(12)) +
               define("popover_bg_color", neutral.get(17)) + define("theme_base_color", neutral.get(17)) +
               define("view_bg_color", neutral.get(17)) + define("theme_fg_color", neutral.get(90)) +
               define("window_fg_color", neutral.get(90)) + define("view_fg_color", neutral.get(90)) +
               define("popover_fg_color", neutral.get(90)) + define("theme_text_color", neutral.get(90)) +
               define("accent_color", primary.get(80)) + define("accent_bg_color", primary.get(80)) +
               define("accent_fg_color", primary.get(20)) + define("theme_selected_bg_color", primary.get(80)) +
               define("theme_selected_fg_color", primary.get(20)) + define("borders", variant.get(30));
    }

    void refresh(const std::string& image) {
        if (image.empty())
            return;
        std::thread([image] {
            const auto argb = seed(image);
            if (!argb) {
                g_warning("palette: cannot derive colours from %s", image.c_str());
                return;
            }
            const std::string out = "/* generated by fenriz-desktop from " + image + " */\n" + css(*argb);
            const std::string path = colors_path();

            // An identical rewrite would still make every watcher reload its sheet.
            gchar* old = nullptr;
            if (g_file_get_contents(path.c_str(), &old, nullptr, nullptr) && out == old) {
                g_free(old);
                return;
            }
            g_free(old);

            char* dir = g_path_get_dirname(path.c_str());
            g_mkdir_with_parents(dir, 0700);
            g_free(dir);
            GError* err = nullptr;
            if (!g_file_set_contents(path.c_str(), out.c_str(), -1, &err)) {
                g_warning("palette: %s: %s", path.c_str(), err->message);
                g_error_free(err);
                return;
            }
            g_message("palette: %s -> %s", image.c_str(), hex(*argb).c_str());
        }).detach();
    }

} // namespace fenriz::desktop::palette
