#!/bin/bash
# Install everything needed to build and test fenriz, on Arch, Fedora or Debian.
#
#   ./scripts/ci-deps.sh
#
# Two of fenriz's dependencies are not packaged anywhere useful: wlroots 0.20 is Arch-only
# (extra/wlroots0.20) and scenefx 0.5 is AUR-only, so both are built from source here when
# pkg-config can't already find them. wayland-protocols is pinned for the same reason the
# other two are: scripts/protocol-audit.sh walks the installed XML, so an older set makes
# that test's result a property of the distro rather than of this repo.
#
# Everything installs into /usr, not /usr/local: Arch's pkgconf does not search
# /usr/local/lib/pkgconfig at all, so a /usr/local install is invisible to the very next
# command unless every caller also exports PKG_CONFIG_PATH. Each distro's libdir is passed
# explicitly ($LIBDIR) rather than left to meson, which guesses /usr/lib64 on Debian — a
# path nothing there searches. This writes outside the package manager, so run it in a
# container or a throwaway machine, not on your desktop.

set -eu

WLROOTS_TAG=0.20.2
SCENEFX_TAG=0.5
WAYLAND_PROTOCOLS_TAG=1.49
WAYLAND_TAG=1.26.0

SRC=$(mktemp -d)
trap 'rm -rf "$SRC"' EXIT

. /etc/os-release

case ${ID_LIKE:-$ID} in
    *arch*|arch)
        LIBDIR=lib
        pacman -Syu --noconfirm --needed \
            base-devel cmake ninja git meson pkgconf \
            wayland wayland-protocols libxkbcommon pixman libinput libdrm mesa \
            libffi expat libxml2 \
            seatd systemd-libs lcms2 libdisplay-info libliftoff hwdata \
            libxcb xcb-util-wm xcb-util-errors \
            wlroots0.20 xorg-xwayland xkeyboard-config socat
        ;;
    *fedora*|fedora)
        LIBDIR=lib64
        dnf install -y \
            gcc-c++ cmake ninja-build git meson pkgconf-pkg-config \
            wayland-devel wayland-protocols-devel libxkbcommon-devel pixman-devel \
            libffi-devel expat-devel libxml2-devel \
            libinput-devel libdrm-devel mesa-libEGL-devel mesa-libGLES-devel \
            mesa-libgbm-devel systemd-devel lcms2-devel \
            libseat-devel libdisplay-info-devel libliftoff-devel hwdata \
            libxcb-devel xcb-util-wm-devel xcb-util-errors-devel \
            xorg-x11-server-Xwayland xorg-x11-server-Xwayland-devel \
            xkeyboard-config socat
        ;;
    *debian*|debian|*ubuntu*|ubuntu)
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y --no-install-recommends \
            g++ cmake ninja-build git meson pkg-config ca-certificates \
            libwayland-dev libwayland-bin wayland-protocols \
            libffi-dev libexpat1-dev libxml2-dev \
            libxkbcommon-dev libpixman-1-dev libinput-dev libdrm-dev \
            libegl-dev libgles-dev libgbm-dev libudev-dev liblcms2-dev \
            libseat-dev libdisplay-info-dev libliftoff-dev hwdata \
            libxcb1-dev libxcb-composite0-dev libxcb-icccm4-dev libxcb-ewmh-dev \
            libxcb-render0-dev libxcb-res0-dev libxcb-xfixes0-dev libxcb-errors-dev \
            xwayland xkb-data socat
        # Debian is multiarch and meson does not infer it: left to its own devices it picks
        # /usr/lib64, which nothing on Debian searches.
        LIBDIR=lib/$(gcc -print-multiarch)
        ;;
    *)
        echo "ci-deps: unsupported distro: ${ID:-unknown}" >&2
        exit 1
        ;;
esac

# Clone shallow at a tag and install over the distro's own copy. Meson's subproject
# fallbacks stay available, so a distro missing an optional wlroots dep still builds.
build_meson() {
    local url=$1 tag=$2 name=$3; shift 3
    echo "==> building $name $tag from source"
    git clone --depth 1 --branch "$tag" "$url" "$SRC/$name"
    meson setup "$SRC/$name/build" "$SRC/$name" \
        --prefix=/usr --libdir="$LIBDIR" --buildtype=release "$@"
    ninja -C "$SRC/$name/build" install
    ldconfig
}

# wayland-scanner has to come first and has to be recent: Debian trixie ships 1.23, whose
# DTD rejects the `frozen` interface attribute used throughout wayland-protocols 1.49, and
# every protocol header in the build is generated by it.
pkg-config --atleast-version=$WAYLAND_TAG wayland-scanner ||
    build_meson https://gitlab.freedesktop.org/wayland/wayland.git \
        "$WAYLAND_TAG" wayland -Dtests=false -Ddocumentation=false

# The audit script reads whatever XML is installed, so an older set changes what the test
# means. Anything at or past the pin is left alone: a distro ahead of us is the case that
# audit is meant to catch.
pkg-config --atleast-version=$WAYLAND_PROTOCOLS_TAG wayland-protocols ||
    build_meson https://gitlab.freedesktop.org/wayland/wayland-protocols.git \
        "$WAYLAND_PROTOCOLS_TAG" wayland-protocols -Dtests=false

# xwayland=enabled is required: src/xwayland.cpp calls wlr_xwayland_create().
# renderers=gles2 drops the vulkan renderer, and with it glslang and the vulkan headers —
# fenriz runs on the GLES2 path (and pixman, headless) only.
pkg-config --exists wlroots-0.20 ||
    build_meson https://gitlab.freedesktop.org/wlroots/wlroots.git \
        "$WLROOTS_TAG" wlroots -Dexamples=false -Dwerror=false \
        -Drenderers=gles2 -Dxwayland=enabled

# Never packaged outside the AUR, so this one always builds.
pkg-config --exists scenefx-0.5 ||
    build_meson https://github.com/wlrfx/scenefx.git \
        "$SCENEFX_TAG" scenefx -Dexamples=false -Dwerror=false

pkg-config --print-errors --exists \
    "scenefx-0.5 wlroots-0.20 wayland-server wayland-client xkbcommon pixman-1 libinput xcb xcb-icccm xcb-ewmh"
echo "==> ready: wlroots $(pkg-config --modversion wlroots-0.20), scenefx $(pkg-config --modversion scenefx-0.5), wayland-protocols $(pkg-config --modversion wayland-protocols)"
